version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.9
  build:
    commands:
    #  - sam package --template-file counter-api-db/template.yml --s3-bucket $BUCKETNAME --output-template-file packaged-template.yml
      - sam build --template-file counter-api-db/template.yml
      - sam deploy --template-file counter-api-db/template.yml --stack-name counter-api-db --no-confirm-changeset --no-fail-on-empty-changeset
artifacts:
  files:
    - packaged-template.yml